# -*- coding: utf-8 -*-
"""AirPassengers DL ASSIGNMENT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oHlnnq-pj9ZhG2NcCnby8IFE3pREa1oM
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense,Dropout,BatchNormalization
from tensorflow.keras.optimizers import Adam
from datetime import timedelta #used to work with time intervals—specifically, to add or subtract days, hours, minutes, etc., from a datetime object.



# Step 1: Load and prepare the data

# Read the CSV file into a pandas DataFrame
# 'parse_dates' ensures the 'Date' column is converted to datetime objects
# 'dayfirst=True' interprets dates in DD-MM-YYYY format
data = pd.read_csv('AirPassengers.csv', parse_dates=['Month'], dayfirst=True)
print(data.head(3))

# Set the 'Date' column as the index of the DataFrame
# This is useful for time series operations like resampling, rolling averages, etc.
data.set_index('Month', inplace=True)

print(data.head(3))

# Use only the 'Close' column from the DataFrame
close_prices = data['#Passengers'].values  # 1D array
print('Before reshape:', close_prices[0:3])

# Convert it to a NumPy array and reshape it into a 2D array with one column,you get a 2D array with shape (n, 1): (No of rows,1 column)
# This format is required for many machine learning models (e.g., scikit-learn, LSTM)
#-1 tells NumPy to infer the number of rows based on the original size.
#1 sets the number of columns to one—making it a column vector.
close_prices = data['#Passengers'].values.reshape(-1, 1)
print(close_prices[0:3])

print(close_prices.shape)

# Normalize the data
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(close_prices)
print(scaled_data[0:3])

# Step 2: Create sequences for time series modeling
def create_sequences(data, seq_length):
    X, y = [], []  # Initialize empty lists for input sequences (X) and targets (y)

    # Loop through the data starting from 'seq_length' to the end
    for i in range(seq_length, len(data)):
        # Extract a sequence of 'seq_length' values ending at position i
        X.append(data[i-seq_length:i])
        # The target value is the one immediately following the sequence
        y.append(data[i])

    # Convert lists to NumPy arrays for model compatibility
    return np.array(X), np.array(y)


# Define the sequence length (number of past time steps to use for prediction)
seq_length = 5

# Create input sequences (X) and corresponding target values (y)
# Each X[i] will contain 5 consecutive scaled prices, and y[i] will be the next price

X, y = create_sequences(scaled_data, seq_length)

print('X Value:',X[0:3])
print('y Value:',y[0:3])

#data['Close'].values by itself is a 1D NumPy array with shape (N,) — just a flat vector of closing prices.
#reshape(-1, 1) converts it into a 2D array with shape (N, 1): N = number of rows (days of data), 1 = one column (the closing price feature)
print('Before reshaping X:', X.shape)

# Reshape X to match the input shape expected by LSTM: (samples, time steps, features)
# Here, each sample has 5 time steps and 1 feature (the scaled closing price)
#Let’s say your original scaled_data has 100 rows (i.e., 100 time steps), and your seq_length is 5. Then:
#You can create 100 - 5 = 95 sequences.
#So X.shape[0] will be 95 → meaning 95 rows (or samples).
#After reshaping: X.shape = (95, 5, 1)

X = X.reshape((X.shape[0], X.shape[1], 1))

print('After reshaping X:', X[0:3])
print('After reshaping X:', X.shape)

#Build a RNN (LSTM) model
model = Sequential([
    # First LSTM layer: returns sequences to feed into the next LSTM
    LSTM(128, return_sequences=True, input_shape=(seq_length, 1)),

    # Dropout: randomly drops 30% of units to prevent overfitting
    Dropout(0.5),

    # BatchNormalization: stabilizes and speeds up training
    #BatchNormalization(),

    # Second LSTM layer: returns final output sequence
    LSTM(64, return_sequences=False),

    # Dropout again, but lighter
    Dropout(0.35),

    # Dense layer: adds non-linearity and learns deeper patterns
    Dense(32, activation='relu'),

    # Output layer: predicts the next value
    Dense(1)
])

from tensorflow.keras.callbacks import EarlyStopping

# Define the early stopping callback
early_stop = EarlyStopping(
    monitor='val_loss',     # What to monitor
    patience=5,             # How many epochs to wait before stopping
    restore_best_weights=True  # Optional: revert to best weights
)

# Compile the model
model.compile(optimizer=Adam(learning_rate=0.001), loss='mean_squared_error',metrics=['mae'])
model.summary()

history = model.fit(X, y, epochs=100, batch_size=16, validation_split=0.2, verbose=0)

import matplotlib.pyplot as plt

# Plot training & validation loss values
plt.figure(figsize=(10, 5))
plt.plot(history.history['loss'], label='Training Loss', color='orange')
plt.plot(history.history['val_loss'], label='Validation Loss', color='red')
plt.title('Model Loss Over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss (MSE)')
plt.legend()
plt.grid(True)
plt.show()

# Step 5: Predict and inverse transform
predicted_prices = model.predict(X)
predicted_prices = scaler.inverse_transform(predicted_prices)
actual_prices = scaler.inverse_transform(y)

# Ensure both arrays are the same length
for i in range(10):  # print first 10 comparisons
    print(f"Day {i+1}: Actual = {actual_prices[i][0]:.2f}, Predicted = {predicted_prices[i][0]:.2f}")

from sklearn.metrics import mean_squared_error
mse = mean_squared_error(actual_prices, predicted_prices)
print("MSE:", mse)

rmse = np.sqrt(mse)
print("RMSE:", rmse)

from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(actual_prices, predicted_prices)
print("MAE:", mae)

from sklearn.metrics import r2_score
r2 = r2_score(actual_prices, predicted_prices)
print("R² Score:", r2)

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))
plt.plot(actual_prices, color='blue', label='Actual Time')
plt.plot(predicted_prices, color='red', label='Predicted Time')
plt.title('Airline Prediction')
plt.xlabel('Month')
plt.ylabel('Passengers')
plt.legend()
plt.show()

### Forecasting Future Months

num_future_months = 5
future_predictions = []

# Get the last 'seq_length' data points from the scaled data to start the prediction
last_sequence = scaled_data[-seq_length:].reshape(1, seq_length, 1)

for _ in range(num_future_months):
    # Predict the next value
    next_prediction_scaled = model.predict(last_sequence, verbose=0)[0]
    future_predictions.append(next_prediction_scaled)

    # Update the sequence: remove the first element and append the new prediction
    # This is crucial for multi-step forecasting
    last_sequence = np.append(last_sequence[:, 1:, :], next_prediction_scaled.reshape(1, 1, 1), axis=1)

# Inverse transform the future predictions to get actual passenger numbers
future_predictions = scaler.inverse_transform(np.array(future_predictions).reshape(-1, 1))

# Generate future dates
last_date = data.index[-1]
future_dates = pd.date_range(start=last_date + pd.DateOffset(months=1), periods=num_future_months, freq='MS')

# Create a DataFrame for future predictions
future_df = pd.DataFrame({'Month': future_dates, '#Passengers': future_predictions.flatten()})
future_df.set_index('Month', inplace=True)

print("Future 5 Months Predictions:")
print(future_df)

### Visualizing Future Predictions

plt.figure(figsize=(15, 7))

# Plot actual historical prices
plt.plot(data.index[seq_length:], actual_prices, color='blue', label='Actual Historical Passengers')

# Plot predicted historical prices
# Note: predicted_prices already has the correct length for the training set (len(data) - seq_length)
plt.plot(data.index[seq_length:], predicted_prices, color='orange', linestyle='--', label='Predicted Historical Passengers')

# Plot future predictions
plt.plot(future_df.index, future_df['#Passengers'], color='red', linestyle='-', marker='o', label='Future Predicted Passengers')

plt.title('Airline Passenger Forecast')
plt.xlabel('Month')
plt.ylabel('Number of Passengers')
plt.legend()
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()